/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Engine } from "./Engine";
import { EngineCountArgs } from "./EngineCountArgs";
import { EngineFindManyArgs } from "./EngineFindManyArgs";
import { EngineFindUniqueArgs } from "./EngineFindUniqueArgs";
import { DeleteEngineArgs } from "./DeleteEngineArgs";
import { EngineService } from "../engine.service";
@graphql.Resolver(() => Engine)
export class EngineResolverBase {
  constructor(protected readonly service: EngineService) {}

  async _enginesMeta(
    @graphql.Args() args: EngineCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Engine])
  async engines(@graphql.Args() args: EngineFindManyArgs): Promise<Engine[]> {
    return this.service.engines(args);
  }

  @graphql.Query(() => Engine, { nullable: true })
  async engine(
    @graphql.Args() args: EngineFindUniqueArgs
  ): Promise<Engine | null> {
    const result = await this.service.engine(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Engine)
  async deleteEngine(
    @graphql.Args() args: DeleteEngineArgs
  ): Promise<Engine | null> {
    try {
      return await this.service.deleteEngine(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
